# Environmental variables for AWS & AWS settings

import os

# AWS settings
AWS_REGION = ""
S3_BUCKET = ""
DYNAMODB_TABLE_ROBOTS = ""
DYNAMODB_TABLE_SCREENSHOTS = ""
DYNAMODB_TABLE_CLIPS = ""

# SECURITY SETTINGS
SECRET_KEY = ""
COGNITO_USER_POOL_ID = ""

